---

language: bash
services: docker

env:
  - VERSION=latest
  - VERSION=stable

install:
  - git clone https://github.com/Teebor-Choka/fastnetmon-docker.git ~/fastnetmon
  - cd ~/fastnetmon

script:
  - ./hooks/build.sh

after_script:
  - docker images
